import type { Categoria, GrupoOpcao, Produto } from './tipos.ts';

export const categorias: { id: Categoria; nome: string }[] = [
  { id: 'cookies', nome: 'Cookies' },
  { id: 'bolos', nome: 'Bolos & Tortas' },
  { id: 'brownies', nome: 'Brownies' },
  { id: 'sazonais', nome: 'Presentes & Sazonais' },
];

export const catalogo: Produto[] = [
  {
    id: 'cookie-pistache',
    nome: 'Cookie de Pistache',
    categoria: 'cookies',
    descricao: 'Cookie recheado com creme de pistache, casquinha crocante e centro macio.',
    precoBase: 6200,
    gruposIds: ['tamanho-caixa'],
    permiteMensagem: false,
    permiteFoto: false,
  },
  {
    id: 'cookie-chocomenta',
    nome: 'Cookie Choco-Menta',
    categoria: 'cookies',
    descricao: 'Massa de chocolate belga com gotas de menta refrescante.',
    precoBase: 5400,
    gruposIds: ['tamanho-caixa'],
    permiteMensagem: false,
    permiteFoto: false,
  },
  {
    id: 'cookie-limao-morango',
    nome: 'Cookie Limão com Morango',
    categoria: 'cookies',
    descricao: 'Massa cítrica de limão siciliano recheada com geleia artesanal de morango.',
    precoBase: 5600,
    gruposIds: ['tamanho-caixa'],
    permiteMensagem: false,
    permiteFoto: false,
  },
  {
    id: 'cookie-choco-laranja',
    nome: 'Cookie Chocolate com Laranja',
    categoria: 'cookies',
    descricao: 'Chocolate meio amargo com raspas de laranja confitada.',
    precoBase: 5600,
    gruposIds: ['tamanho-caixa'],
    permiteMensagem: false,
    permiteFoto: false,
  },
  {
    id: 'cookie-brigadeiro-bacon',
    nome: 'Cookie Brigadeiro com Bacon',
    categoria: 'cookies',
    descricao: 'O clássico da casa: brigadeiro cremoso com lascas crocantes de bacon.',
    precoBase: 6000,
    gruposIds: ['tamanho-caixa'],
    permiteMensagem: false,
    permiteFoto: false,
  },
  {
    id: 'cookie-amendoim',
    nome: 'Cookie de Amendoim',
    categoria: 'cookies',
    descricao: 'Pasta de amendoim caseira e amendoim torrado em pedaços.',
    precoBase: 5200,
    gruposIds: ['tamanho-caixa'],
    permiteMensagem: false,
    permiteFoto: false,
  },
  {
    id: 'cookie-sonho-de-valsa',
    nome: 'Cookie Sonho de Valsa',
    categoria: 'cookies',
    descricao: 'Recheio cremoso de Sonho de Valsa com pedaços do bombom na massa.',
    precoBase: 5800,
    gruposIds: ['tamanho-caixa'],
    permiteMensagem: false,
    permiteFoto: false,
  },
  {
    id: 'bolo-chocolate',
    nome: 'Bolo de Chocolate Tradicional',
    categoria: 'bolos',
    descricao: 'Massa de chocolate fofinha, recheio à sua escolha e acabamento clássico.',
    precoBase: 12000,
    gruposIds: ['tamanho-bolo', 'sabor-massa', 'recheio', 'cobertura'],
    permiteMensagem: true,
    permiteFoto: false,
  },
  {
    id: 'bolo-decorado',
    nome: 'Bolo Decorado',
    categoria: 'bolos',
    descricao: 'Bolo temático feito sob medida para a sua festa. Envie uma foto de referência.',
    precoBase: 18500,
    gruposIds: ['tamanho-bolo', 'sabor-massa', 'recheio', 'cobertura'],
    permiteMensagem: true,
    permiteFoto: true,
  },
  {
    id: 'brownie',
    nome: 'Brownie Tradicional',
    categoria: 'brownies',
    descricao: 'Brownie denso de chocolate 70%, casquinha craquelada e centro úmido.',
    precoBase: 4500,
    gruposIds: ['tamanho-caixa'],
    permiteMensagem: false,
    permiteFoto: false,
  },
  {
    id: 'buque-doces',
    nome: 'Buquê de Doces',
    categoria: 'sazonais',
    descricao: 'Arranjo de doces finos montado como buquê. Acompanha cartão personalizado.',
    precoBase: 8900,
    gruposIds: ['tamanho-buque'],
    permiteMensagem: true,
    permiteFoto: false,
  },
  {
    id: 'ovo-pascoa',
    nome: 'Ovo de Páscoa Recheado',
    categoria: 'sazonais',
    descricao: 'Ovo de colher com casca de chocolate nobre e recheio à sua escolha.',
    precoBase: 7500,
    gruposIds: ['tamanho-ovo', 'recheio'],
    permiteMensagem: true,
    permiteFoto: false,
  },
  {
    id: 'panetone',
    nome: 'Panetone Artesanal',
    categoria: 'sazonais',
    descricao: 'Panetone de fermentação natural, recheado com brigadeiro ou doce de leite.',
    precoBase: 6800,
    gruposIds: ['recheio'],
    permiteMensagem: false,
    permiteFoto: false,
  },
  {
    id: 'biscoito-natal',
    nome: 'Biscoito de Natal Pintado',
    categoria: 'sazonais',
    descricao: 'Biscoitos amanteigados decorados à mão com glacê real.',
    precoBase: 5800,
    gruposIds: ['tamanho-caixa'],
    permiteMensagem: false,
    permiteFoto: true,
  },
];

export const grupos: Record<string, GrupoOpcao> = {
  'tamanho-caixa': {
    id: 'tamanho-caixa',
    titulo: 'Tamanho da caixa',
    obrigatorio: true,
    opcoes: [
      { id: 'caixa-6', nome: 'Caixa com 6', delta: 0 },
      { id: 'caixa-12', nome: 'Caixa com 12', delta: 4800 },
      { id: 'caixa-24', nome: 'Caixa com 24', delta: 9000 },
    ],
  },
  'tamanho-bolo': {
    id: 'tamanho-bolo',
    titulo: 'Tamanho',
    obrigatorio: true,
    opcoes: [
      { id: 'bolo-1kg', nome: '1 kg — 15 fatias', delta: 0 },
      { id: 'bolo-1-5kg', nome: '1,5 kg — 25 fatias', delta: 5500 },
      { id: 'bolo-2kg', nome: '2 kg — 35 fatias', delta: 10500 },
    ],
  },
  'tamanho-buque': {
    id: 'tamanho-buque',
    titulo: 'Tamanho do buquê',
    obrigatorio: true,
    opcoes: [
      { id: 'buque-p', nome: 'Pequeno — 9 doces', delta: 0 },
      { id: 'buque-m', nome: 'Médio — 15 doces', delta: 3500 },
      { id: 'buque-g', nome: 'Grande — 24 doces', delta: 7000 },
    ],
  },
  'tamanho-ovo': {
    id: 'tamanho-ovo',
    titulo: 'Peso',
    obrigatorio: true,
    opcoes: [
      { id: 'ovo-350', nome: '350 g', delta: 0 },
      { id: 'ovo-500', nome: '500 g', delta: 3800 },
      { id: 'ovo-750', nome: '750 g', delta: 8500 },
    ],
  },
  'sabor-massa': {
    id: 'sabor-massa',
    titulo: 'Sabor da massa',
    obrigatorio: true,
    opcoes: [
      { id: 'massa-chocolate', nome: 'Chocolate', delta: 0 },
      { id: 'massa-baunilha', nome: 'Baunilha', delta: 0 },
      { id: 'massa-cenoura', nome: 'Cenoura', delta: 0 },
      { id: 'massa-red-velvet', nome: 'Red velvet', delta: 1500 },
    ],
  },
  recheio: {
    id: 'recheio',
    titulo: 'Recheio',
    obrigatorio: true,
    opcoes: [
      { id: 'recheio-brigadeiro', nome: 'Brigadeiro', delta: 0 },
      { id: 'recheio-doce-leite', nome: 'Doce de leite', delta: 800 },
      { id: 'recheio-maracuja', nome: 'Mousse de maracujá', delta: 1200 },
      { id: 'recheio-ninho-nutella', nome: 'Ninho com Nutella', delta: 2200 },
    ],
  },
  cobertura: {
    id: 'cobertura',
    titulo: 'Cobertura',
    obrigatorio: false,
    opcoes: [
      { id: 'cobertura-nenhuma', nome: 'Sem cobertura', delta: 0 },
      { id: 'cobertura-chantilly', nome: 'Chantilly', delta: 1500 },
      { id: 'cobertura-ganache', nome: 'Ganache', delta: 2500 },
      { id: 'cobertura-pasta', nome: 'Pasta americana', delta: 4500 },
    ],
  },
};

/**
 * Traduz as seleções (que guardam ids) para pares legíveis, na ordem em que os
 * grupos aparecem no produto. Usado por todas as telas de resumo.
 */
export function buscarProduto(id: string): Produto | undefined {
  return catalogo.find((p) => p.id === id);
}
